### ISSUE TITLE
x86?

### ISSUE THREAD

**Issue by kj7rrv** [rreilink/PiPyOS#3]
Could the build be modified for X86?

**Comment by rreilink** [comment]
Actually PiPyOS was inspired by a project that does this. Have a look at: [Intel BIOS BITS](https://biosbits.org/scripting/)

**Comment by kj7rrv** [comment]
Cool! Thanks! That with 3to2 should do what I'd need.

**Comment by kj7rrv** [comment]
Does that mean I could write an OS in Python with BITS?
